# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

private_lane :next_release_build_number do
  current_project_build = get_build_number(
    xcodeproj: "VaultApp/VaultApp.xcodeproj"
  ).to_i

  latest_uploaded_build = latest_testflight_build_number(
    app_identifier: "com.badbundle.vault",
    username: "badbundlelimited@gmail.com",
    team_id: "127471357",
    platform: "ios",
    initial_build_number: current_project_build
  ).to_i

  ([current_project_build, latest_uploaded_build].max + 1).to_s
rescue => error
  UI.user_error!("Unable to determine the next App Store build number: #{error.message}")
end

desc "Prints the next global App Store/TestFlight build number without changing project files"
lane :increment_build do
  build_number = next_release_build_number
  UI.message("Next release build number: #{build_number}")
  build_number
end

platform :ios do
  desc "Push a new release build to the App Store"


  lane :release do
    ensure_git_status_clean
    release_build_number = next_release_build_number
    UI.message("Using release build number #{release_build_number}")

    get_certificates
    get_provisioning_profile(app_identifier: "com.badbundle.vault")
    get_provisioning_profile(app_identifier: "com.badbundle.vault.VaultAutofill")
    get_provisioning_profile(app_identifier: "com.badbundle.vault.Widgets")

    # Build and export - skip validation during export to avoid auth issues
    gym(
      workspace: "Vault.xcworkspace",
      scheme: "VaultApp",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.badbundle.vault" => "vault.mobileprovision",
          "com.badbundle.vault.VaultAutofill" => "vault-autofill.mobileprovision",
          "com.badbundle.vault.Widgets" => "vault-widgets.mobileprovision"
        },
        uploadSymbols: true,
        uploadBitcode: false,
        # This is the key - skip the Apple validation during export
        manageAppVersionAndBuildNumber: false
      },
      clean: true,
      export_team_id: "442P244AFS",
      # Use xcargs to pass additional options
      xcargs: "-allowProvisioningUpdates CURRENT_PROJECT_VERSION=#{release_build_number}"
    )
    
    # Upload to App Store using the correct Apple ID
    upload_to_app_store(
      username: "badbundlelimited@gmail.com",
      team_id: "442P244AFS"
    )
  end

  desc "Upload the existing VaultApp.ipa to App Store Connect (no build, no bump)"
  lane :upload do
    upload_to_app_store(
      ipa: "./VaultApp.ipa",
      skip_metadata: true,
      skip_screenshots: true
    )
  end
end
